### ISSUE TITLE
Prefer destruction in must cases

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1096]
Don't:

``` ts
const goals = data?.goals;
const meta = data?.meta;
```

Do:

``` ts
const { goals, meta } = data || {}
```

**Comment by 9teen90nine** [comment]
Try to enable `"prefer-destructuring": "error"` and check errors - they are probably fixable with prettier --fix

(Looks like an awful lot of prettier errors are currently in the code)
