### ISSUE TITLE
Support @pevious, @current, @next in estimate filters

### ISSUE THREAD

**Issue by 9teen90nine** [taskany-inc/issues#1134]
Should filter by currently running estimate including yearly ones and also should work in saved presets

**Comment by awinogradov** [comment]
![Image](https://github.com/taskany-inc/issues/assets/982072/cf588d6b-255b-41f0-a15b-04cf7ec5525a)

**Comment by sab94a** [comment]
after #1627

**Comment by 9teen90nine** [comment]
PR: #1658
