### ISSUE TITLE
Send to Crew profile when username is clicked

### ISSUE THREAD

**Issue by Troff8** [taskany-inc/issues#1149]
- add env var domain abc
![Wz2dBSq9xMo](https://github.com/taskany-inc/issues/assets/87986652/2ab5d7fa-06c4-4fc2-8d4b-c6c06753b966)

**Comment by 9teen90nine** [comment]
1. If passed PROFILE_URL env, wrap userpic in Link to this env + urlencoded email
2. If not - don't wrap in Link
