### ISSUE TITLE
FiltersPanel is broken in ru locale

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1235]
<img width="1502" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/1cbc2a49-eebc-44c2-b392-646c9e6a7fa0">

**Comment by awinogradov** [comment]
![Image](https://github.com/taskany-inc/issues/assets/982072/f2a404fd-0d98-435c-97b3-bed6c720b2a2)

**Comment by 9teen90nine** [comment]
Depends on #1367
