### ISSUE TITLE
New project/goal must opens in _blank page

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#133]
No redirect from page where Modal was opened.

**Comment by sumitsaurabh927** [comment]
Can I work on this?

**Comment by awinogradov** [comment]
@sumitsaurabh927 sure! you can. We are open for any contributions ;)

**Comment by sumitsaurabh927** [comment]
Please assign me then @awinogradov 🌟

**Comment by awinogradov** [comment]
@sumitsaurabh927 you can start with draft PR. If it would be ok, I'll assign you, no problem.

**Comment by sumitsaurabh927** [comment]
Okay, lemme work on it then!
