### ISSUE TITLE
Hide projects w/o goals on project/projects pages if filters applied

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1336]
When a filter is applied that filters out all goals in the project, the project should be hidden.

May be useful: https://www.prisma.io/docs/concepts/components/prisma-client/aggregation-grouping-summarizing#filtered-count

NB!: project can have not only goals, but also parent projects without goals that still should be shown.

**Comment by 9teen90nine** [comment]
Looks like it was fixed during long-term dashboard bug fixing strategy
