### ISSUE TITLE
Rewrite raw sql for projects

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1418]
https://github.com/taskany-inc/issues/blob/main/trpc/queries/sqlProject.ts

https://github.com/taskany-inc/issues/blob/main/trpc/router/project.ts#L127

Possible way to solve:
Update project on goal updates, like https://github.com/taskany-inc/issues/blob/main/trpc/router/goal.ts#L902
And make simple query with orderBy updatedAt on project.

**Comment by sab94a** [comment]
Also we had a missed parameter `firstLevel`, which should return us only projects without parent

https://github.com/taskany-inc/issues/blob/main/trpc/router/project.ts#L118

**Comment by sab94a** [comment]
Also the search results order depends from applied filters (should be independent)
