### ISSUE TITLE
E2E: Goal /create

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1642]
- ways to open dialog: menu/hotkey
- clean fields at first time 
- title and project is required, form can't be submitted
- title can be located on goal page
- description is empty by default
  - placeholder in empty case
  - description in filled case
- project
  - empty by default
  - current project from project page
  - most used project in case of some created goals
- priority is Medium by default, change is available and can be located on goal page
- owner is current user by default, change is available and can be located on goal page
- state is Draft by default, change is available and can be located on goal page
- estimate is empty by default, change is available and can be located on goal page (any kind: year, quarter, exact date)
- ways to create
  - create only
  - create and go
  - create one more

**Comment by LamaEats** [comment]
> state is Draft by default, change is available and can be located on goal page

state isn't selected and disabled by default while user doesn't selected project

fyi @awinogradov

**Comment by awinogradov** [comment]
@LamaEats yep. Because Flow with states depends on the project.
