### ISSUE TITLE
Goal deps redesign 

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1709]
**Before** 

<img width="340" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/c9149af3-aef0-40c0-8313-1ed54ff47063">

**After**

<img width="652" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/fa95dd5a-0ba2-4a92-8ffc-7c790cdcc13b">

Also fix this 
<img width="285" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/15ac8bec-f69b-45a2-970d-fee82b85600a">

**Comment by 9teen90nine** [comment]
Add goal as dependent on click and redraw live

**Comment by awinogradov** [comment]
Move deps to sidebar
