### ISSUE TITLE
Collect same history records in view

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1753]
<img width="301" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/1895416f-454c-4803-b732-05df8419c011">

<img width="628" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/75ec6895-8c99-4e9b-b831-c0edf14ddf65">

**Comment by 9teen90nine** [comment]
1. Collect items with the same type which stand in a row to a group 
2. Show count, authors combined, last timestamp
