### ISSUE TITLE
Current state for push comment by default

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1755]
<img width="685" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/f95e9410-0ea7-4cd4-890a-bc21c58943ea">

**Comment by 9teen90nine** [comment]
Color: primary

![Image](https://github.com/taskany-inc/issues/assets/3691805/de9f5a7e-0f56-4b72-9d16-b1caf28c5a9f)
