### ISSUE TITLE
Remove/rewrite superjson

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1763]
Problem: too big json data on client. This is the result of Date serialization from SSR. Diff btw SSR and CSR 200+ ms in TFP. This is the big performance issue.

Experiment #1728

![image](https://github.com/taskany-inc/issues/assets/982072/2de7d49e-4569-4fb6-b52f-b7a28df9bad7)

**Comment by tsumo** [comment]
https://github.com/taskany-inc/issues/tree/custom-transformer
