### ISSUE TITLE
Move fully copied handlers to useGoalsResources

### ISSUE THREAD

**Issue by DenisVorop** [taskany-inc/issues#1853]
components:

1) GoalPreview
2) GoalPage

handlers:

1) onGoalTagAdd
2) onGoalTagRemove
3) onGoalTransfer

**Comment by 9teen90nine** [comment]
https://github.com/taskany-inc/issues/blob/main/src/components/GoalPreview/GoalPreview.tsx#L70-L104

A hook like `useUpdateGoalResource` may be created containing all edit goal functions
