### ISSUE TITLE
Timeline is done

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1906]
<img width="80" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/3d10ff30-6f77-4be7-8321-1566bde9e0f5">

**Comment by LamaEats** [comment]
Cannot reproduce in my own browser (Chrome 117.0.5938.149). Which browser have this behavior?

**Comment by LamaEats** [comment]
I cannot reproduce this bug in four different browsers
