### ISSUE TITLE
RU to EN in project key

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1917]
<img width="877" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/9f70feac-d8de-47b6-97e3-a0929ee3ef21">

<img width="850" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/9b43d9d5-b009-47c7-b2c1-b60b69c2c493">

**Comment by 9teen90nine** [comment]
keypredictor should support transliteration
