### ISSUE TITLE
Sync new goal criteria & deps forms

### ISSUE THREAD

**Issue by DenisVorop** [taskany-inc/issues#1990]
- new goal criteria form - https://github.com/taskany-inc/issues/pull/1964
- new goal deps form - https://github.com/taskany-inc/issues/pull/1939

they should look and work the same, no copy-paste

**Comment by 9teen90nine** [comment]
Should create a new base component for both forms.

NB: should be an option for the form not to show radio buttons at all (ex. when adding new dependency from "dependent" block)
