### ISSUE TITLE
Add filters and search to goals page

### ISSUE THREAD

**Issue by peter-nikitin** [taskany-inc/issues#204]
Filters:
- search by name and description (dummy search) 
- state of goal: draft, open 
- issuer (author in figma)
- owner (assignee in model)
- tags (label in figma) 
- sort by date (toggle desc - asc) 

# Dod
- page with list of goals has filters and search  
- you can get filtered goals

**Comment by awinogradov** [comment]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/982072/179959711-e37ae6c0-ec1e-4358-9acd-cfffb767498e.png">
