### ISSUE TITLE
 New create goal form - personal goal switch

### ISSUE THREAD

**Issue by asabotovich** [taskany-inc/issues#2095]
find nice ui solution

**Comment by awinogradov** [comment]
<img width="654" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/60f43fb5-029a-444f-a35e-a3959710ae86">
<img width="668" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/71ce7470-925c-4c63-b00c-e66ab45fc147">

**Comment by 9teen90nine** [comment]
1) Build new form without switch - it should be just the same as current, but without styled-components and with new styles
2) Should add type switch and remove old menu trigger code in another issue #2162
