### ISSUE TITLE
Overview team in project — crew integration

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#2215]
What:
- team title
- people count
- link to team page

How:
- field with team id in project settings

**Comment by 9teen90nine** [comment]
1. Crew API for getting teams (with search) - https://github.com/taskany-inc/crew/issues/432
2. Create a combobox on project settings page to link the project to a crew team
3. Inherit linked team for child projects by default, but support ovveride
4. Show quick summary about the team
