### ISSUE TITLE
Kysely: do not use prisma as query builder

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#2286]
After research in #1854 

Must be resolved step by step:
- [x] setup pg and kysley
- [ ] rewrite all simple queries
- [ ] rewrite simple transactions
- [ ] rewrite raw queries with kysely to typed queries
- [ ] remove prisma client generator from deps and prisma.schema

Could probably also fix https://github.com/taskany-inc/issues/issues/2324

**Comment by 9teen90nine** [comment]
Could probably also fix #2324
