### ISSUE TITLE
Configure autofocus in inputs

### ISSUE THREAD

**Issue by DenisVorop** [taskany-inc/issues#2384]

**Comment by asabotovich** [comment]
- first input inside modal (create modals, remove goal modal)
- ?

**Comment by DenisVorop** [comment]
> autofocus is defined to work reliably only on page load. It is not really suited for situations where you are swapping, or opening, or unhiding DOM elements such as in a single-page application framework. You are likely to have to resort to handling the autofocusing yourself.

- https://github.com/taskany-inc/issues/blob/main/src/components/ProjectCreateForm/ProjectCreateForm.tsx#L53-L55
- https://github.com/taskany-inc/issues/blob/main/src/components/GoalForm/GoalForm.tsx#L133-L135
