### ISSUE TITLE
Prevent unexpected project cache in Localstorage

### ISSUE THREAD

**Issue by asabotovich** [taskany-inc/issues#2534]
Problem:

- create project (will be saved in LS)
- delete project from other computer/browser (in real case - other person)
- project will be in suggested in GoalCreateForm

Places:

```js
useLocalStorage('lastProjectCache')
useLocalStorage('currentProjectCache')
useLocalStorage('recentProjectsCache', {})
```

**Comment by 9teen90nine** [comment]
should reuse sidebar query and remove ls cache at all
nb: check that the current project is selected when creating goal from project page.
