### ISSUE TITLE
Fix GoalTableList item

### ISSUE THREAD

**Issue by LamaEats** [taskany-inc/issues#2548]
User list and status dot aling

**Comment by asabotovich** [comment]
![2024-04-02 13 49 37](https://github.com/taskany-inc/issues/assets/9020793/90fb6d71-dbb3-46a9-bdc4-5dc7dfe3ea90)
![2024-04-02 13 49 50](https://github.com/taskany-inc/issues/assets/9020793/f1693235-d724-4a36-9d8c-de66a5eb5af0)
