### ISSUE TITLE
Text from `@bricks/harmony`

### ISSUE THREAD

**Issue by asabotovich** [taskany-inc/issues#2577]
Big task

**Comment by DenisVorop** [comment]
- https://github.com/taskany-inc/issues/blob/main/src/components/GoalDeleteModal/GoalDeleteModal.tsx#L3
- https://github.com/taskany-inc/issues/blob/main/src/components/FilterDeleteForm/FilterDeleteForm.tsx#L2
- https://github.com/taskany-inc/issues/blob/main/src/components/KeyInput/KeyInput.tsx#L2
- https://github.com/taskany-inc/issues/blob/main/src/components/ProjectCreateForm/ProjectCreateForm.tsx#L5
