### ISSUE TITLE
Return aliases to estimate filter

### ISSUE THREAD

**Issue by asabotovich** [taskany-inc/issues#2581]
![telegram-cloud-photo-size-2-5233423663586466203-y](https://github.com/taskany-inc/issues/assets/9020793/061f2ac1-0715-49f7-95ae-6fcf313e8c91)

**Comment by asabotovich** [comment]
Additional: Also fix markup
![telegram-cloud-photo-size-2-5233423663586466227-x](https://github.com/taskany-inc/issues/assets/9020793/9c43b365-7f8c-47cd-853d-d424e9a94c2f)

**Comment by 9teen90nine** [comment]
also the year input probably could fit the year
