### ISSUE TITLE
Fix counter in history item

### ISSUE THREAD

**Issue by asabotovich** [taskany-inc/issues#2622]
<img width="736" alt="Screenshot 2024-04-16 at 12 37 33" src="https://github.com/taskany-inc/issues/assets/9020793/b32fc4dc-5f04-4aae-bed0-0695dc82e1b1">

**Comment by asabotovich** [comment]
also check markup
![telegram-cloud-photo-size-2-5256060516353301307-x](https://github.com/taskany-inc/issues/assets/9020793/d8cfbb2c-0191-4df0-98dc-3110bc2eba3c)

**Comment by DenisVorop** [comment]
fix in https://github.com/taskany-inc/issues/pull/2633
