### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by nataschachu** [taskany-inc/issues#268]
<img width="342" alt="Снимок экрана 2022-10-03 в 18 11 23" src="https://user-images.githubusercontent.com/1312604/193612663-41875af4-90cc-4281-b6e7-905207b56d18.png">

1. I dont want to receive notifications about my own comments :)
2. wanna more details - real comment message or preview, also notifications title should not be 'Hello'))

**Comment by awinogradov** [comment]
- new comment if: watched, owner, participant
- edited:  watched, owner, participant
- state changed:  watched, owner, participant

**Comment by awinogradov** [comment]
#911
