### ISSUE TITLE
Add priority field to goals

### ISSUE THREAD

**Issue by Yeti-or** [taskany-inc/issues#290]
We could take standard options:

- Highest
- High
- Medium
- Low
- Lowest

relevant icons for priority would be appreciated 

on next step we could add ability to create custom dictionary of priorities for each project

**Comment by awinogradov** [comment]
![image](https://user-images.githubusercontent.com/982072/197058908-a8b3ff3e-f4f7-4b35-9afe-5fe42aef33ac.png)
