### ISSUE TITLE
Setup Storybook

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#31]
https://storybook.js.org/docs/react/get-started/install

**NB:** must works with themes.

**Comment by peter-nikitin** [comment]
Dod:
- storybook запускается локально
- в нем есть минимум 1 сторя
- в этой сторе переключается светаля и темная тема

**Comment by awinogradov** [comment]
🇷🇺 lang detected ;)

**Comment by peter-nikitin** [comment]
> 🇷🇺 lang detected ;)

Whoops
