### ISSUE TITLE
Comment text doesn't disapear after submit

### ISSUE THREAD

**Issue by nataschachu** [taskany-inc/issues#310]
<img width="910" alt="Снимок экрана 2022-10-21 в 11 55 05" src="https://user-images.githubusercontent.com/1312604/197155910-76212aa8-7e23-4bd1-a75b-d812c7a7b527.png">

**Comment by awinogradov** [comment]
Related to #217

**Comment by awinogradov** [comment]
So! This happens because we have a server error in time of comment is publishing. 
Code here https://github.com/taskany-inc/issues/blob/main/graphql/resolvers/Comment.ts#L58 waits MAIL_USER variable from env. But it not passed from Docker in build time `\_(ツ)_/¯`

cc @InnaAndreeva

**Comment by awinogradov** [comment]
Also, it's way we don't have emails about new comments for goals ;)
