### ISSUE TITLE
Добавить запятую после "следите"

### ISSUE THREAD

**Issue by nataschachu** [taskany-inc/issues#314]
<img width="1124" alt="Снимок экрана 2022-10-21 в 19 10 36" src="https://user-images.githubusercontent.com/1312604/197241215-7ac3f77f-0b43-40b3-92c3-d14a0d1d0210.png">

**Comment by nataschachu** [comment]
а вообще лучше звучит "Здесь будут все созданные вами, назначенные на вас, а также цели и проекты, за которыми вы следите"

**Comment by awinogradov** [comment]
🙏🏼
