### ISSUE TITLE
После разлогинивания невозможно снова залогиниться

### ISSUE THREAD

**Issue by nataschachu** [taskany-inc/issues#318]
Шаги: 
* разлогиниваемся через "Выйти"
* заходим на морду, там редирект на ru https://goals.tools.sberdevices.ru/ru
* почему-то снова есть "Выйти" в меню
<img width="1557" alt="Снимок экрана 2022-10-26 в 18 45 25" src="https://user-images.githubusercontent.com/1312604/198073145-9fb9bd53-4afb-47d8-ba21-8dcd2814bc59.png">
* любые переходы по меню, например, на Обзор или Цели, ведут на 404 https://goals.tools.sberdevices.ru/ru/api/auth/signin

Залогиниться в итоге можно только, если убрать ru из урла, вот так https://goals.tools.sberdevices.ru/api/auth/signin

**Comment by awinogradov** [comment]
Проблема связана с локализацией. nextjs-auth как-то криво обрабатывает i18n страницы.
