### ISSUE TITLE
Markdown: add mentions support

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#434]
https://github.com/zestedesavoir/zmarkdown/tree/HEAD/packages/remark-ping

**Comment by 9teen90nine** [comment]
1) Create an autocomplete popup on @ (and an api for the autocomplete) 
2) If lib supports emails - create external link via email
2b) if it doesn't - create a new route returning a redirect to external page

**Comment by 9teen90nine** [comment]
Should be a component for a Link that has an email. Also non-found users can be mentioned via email.

**Comment by asabotovich** [comment]
- https://github.com/taskany-inc/issues/issues/2738
- https://github.com/taskany-inc/issues/issues/2739
- https://github.com/taskany-inc/issues/issues/2740
