### ISSUE TITLE
Нет тултипа об обязательности поля "Описание" при создании проекта

### ISSUE THREAD

**Issue by dakhetov** [taskany-inc/issues#623]
**Describe the bug**
При создании проекта нет тилтипа об обязательности поля "Описание".

**To Reproduce**
1. Нажать на пункт выпадающего меню "Проект" рядом с кнопкой "Создать" в шапке
2. В модальном окне создания проекта заполнить название проекта
3. Нажать на кнопку "Создать проект"

**Expected behavior**
Появился тултип об обязательности заполнения поля "Описание"

**Comment by awinogradov** [comment]
https://user-images.githubusercontent.com/982072/221249610-689d630d-2dc1-402b-b724-f085f8812027.mov
