### ISSUE TITLE
При длинном названии проекта кнопка "Создать цель" скрыта

### ISSUE THREAD

**Issue by dakhetov** [taskany-inc/issues#624]
**Describe the bug**
Если у проекта слишком длинное название (примерно 51 символ), то при создании цели для него, кнопка "Создать цель" будет за пределами модального окна.

**To Reproduce**
1. Создать проект с длинным названием, не менее 51-го символа
2. При создании цели указать этот проект

**Expected behavior**
Кнопка "Создать цель" видна на экране и ее можно нажать
![image](https://user-images.githubusercontent.com/18137315/220595146-e13cb48b-2d3f-4f66-be97-ce0f25bee985.png)

**Comment by awinogradov** [comment]
@dakhetov спасибочки!
