### ISSUE TITLE
Deleted tags come back after deleting in GoalCreateForm and GoalEditForm

### ISSUE THREAD

**Issue by dakhetov** [taskany-inc/issues#661]
https://github.com/taskany-inc/issues/assets/982072/c52f4992-2584-4cab-8e71-524042a71640

**Comment by awinogradov** [comment]
#111

**Comment by awinogradov** [comment]
https://github.com/taskany-inc/issues/assets/982072/c52f4992-2584-4cab-8e71-524042a71640
