### ISSUE TITLE
Light/Dark color generator

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#71]
So, add module like https://github.com/rockbeenorth/colorize/blob/main/getColor.js with API:
``` ts
const [light, dark] = getColor(14, 9);
// console.log(light, dark); 
// ['hsl(14, 90%, 90%)', 'hsl(14, 80%, 12%)']
```

Use this module to generate universal colors pallet for dark and light themes. "Declare once use twice". No handmade colors for themes anymore.

**Comment by rockbeenorth** [comment]
Please use https://www.npmjs.com/package/color-layer to get layered colors for light/dark modes.
